FROM ubuntu:focal

LABEL maintainer="kioz.wang (never.had@outlook.com)"

RUN sed -i 's/archive\.ubuntu\.com/mirrors\.tuna\.tsinghua\.edu\.cn/g;s/security\.ubuntu\.com/mirrors\.tuna\.tsinghua\.edu\.cn/g' /etc/apt/sources.list
ARG DEBIAN_FRONTEND=noninteractive
RUN apt update && apt -y upgrade \
    && rm -rf /var/lib/apt/lists/*

RUN apt update && apt -y install apt-utils dialog iproute2 \
    && rm -rf /var/lib/apt/lists/*

ENV TZ=Asia/Shanghai
RUN apt update && apt -y install tzdata \
    && rm -rf /var/lib/apt/lists/* \
    && ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} >/etc/timezone

RUN apt update && apt -y install python3-pip \
    && rm -rf /var/lib/apt/lists/* \
    && pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

RUN sed -i 's/#force_color_prompt=yes/force_color_prompt=yes/g' /root/.bashrc \
    && echo "root:123" | chpasswd
COPY .toolchain.env.sh /opt/.toolchain.env
RUN echo "source /opt/.toolchain.env" >>/root/.bashrc

ENV LC_ALL=C.UTF-8

COPY .launch.sh /root/
RUN chmod u+x /root/.launch.sh
WORKDIR /root
CMD [ "/root/.launch.sh" ]

RUN apt update && apt -y install openssh-server \
    && rm -rf /var/lib/apt/lists/* \
    && echo '\n\
PermitRootLogin yes\n' \
        >>/etc/ssh/sshd_config \
    && sed -i 's/#Port 22/Port 10022/g' /etc/ssh/sshd_config
COPY authorized_keys /root/.ssh/
EXPOSE 10022

# RUN apt update && apt -y install vim \
#     && rm -rf /var/lib/apt/lists/*
# COPY .vimrc /root/

RUN apt update && apt -y install libncursesw5 cmake ninja-build bear clangd \
    && rm -rf /var/lib/apt/lists/*
